### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by tonygil** [konnektiv/badgeos-achievement-shortcode-add-on#1]
Hi 
I have setup a page with this shortcode, but it does not display anything

[user_earned_achievement id="badges" ][/user_earned_achievement]

Any solution to the program

Tony

**Comment by cherbst** [comment]
Dear Tony,

as the Readme states: 

> Any content in a post or page enclosed in the shortcode [user_earned_achievement id="achievement_id"][/user_earned_achievement] will only be shown if the current user has already earned the achievement with the specified id.

So if you do not enclose any content inside you shortcode, nothing will be shown even if the user has earned the achievement.
